#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ColorBlocks;

/// <summary>
/// Shipped SHA256 catalog of official level files. Mismatch → reject load
/// (unless developer mode). Regenerated by BuildTools/Generate-OfficialManifest.ps1.
/// </summary>
public static class OfficialLevelManifest
{
    public const string ManifestFileName = "manifest.json";

    private static readonly object LoadLock = new();
    private static Dictionary<string, string>? _hashes;
    private static bool _loadAttempted;
    private static readonly Dictionary<string, (long WriteTicks, long Length, string Hash)> HashCache =
        new(StringComparer.OrdinalIgnoreCase);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    public static string ManifestPath =>
        Path.Combine(LevelContentPaths.GetLevelsRoot(LevelSource.Official), ManifestFileName);

    public static void ResetCache()
    {
        lock (LoadLock)
        {
            _hashes = null;
            _loadAttempted = false;
            HashCache.Clear();
        }
    }

    public static bool TryGetExpectedHash(string fileStem, out string hash)
    {
        EnsureLoaded();
        hash = string.Empty;
        if (_hashes is null)
        {
            return false;
        }

        return _hashes.TryGetValue(fileStem, out hash!);
    }

    /// <summary>
    /// Verifies on-disk bytes against the shipped manifest.
    /// Returns true when developer mode (bypass), when manifest missing (warn+allow),
    /// or when hash matches. Returns false on mismatch.
    /// </summary>
    public static bool VerifyLevelFile(string levelId, string filePath, out string reason)
    {
        reason = string.Empty;

        if (DeveloperSettings.DeveloperMode)
        {
            return true;
        }

        if (!LevelIdentity.TryParse(levelId, out LevelSource source, out string fileStem)
            || source != LevelSource.Official)
        {
            return true;
        }

        EnsureLoaded();
        if (_hashes is null || _hashes.Count == 0)
        {
            DiagnosticsLog.Info("OfficialManifest", "Manifest missing or empty — allowing official load");
            return true;
        }

        if (!_hashes.TryGetValue(fileStem, out string? expected) || string.IsNullOrEmpty(expected))
        {
            reason = $"Official level '{fileStem}' is not listed in the integrity manifest.";
            return false;
        }

        if (!File.Exists(filePath))
        {
            reason = $"Official level file missing: {filePath}";
            return false;
        }

        string actual = ComputeFileHash(filePath);
        if (!string.Equals(actual, expected, StringComparison.OrdinalIgnoreCase))
        {
            reason =
                "Official level files were modified. Use Steam → Properties → " +
                "Installed Files → Verify integrity of game files.";
            DiagnosticsLog.Info(
                "OfficialManifest",
                $"Hash mismatch level={levelId} expected={expected} actual={actual}");
            return false;
        }

        return true;
    }

    public static string ComputeFileHash(string filePath)
    {
        var info = new FileInfo(filePath);
        long writeTicks = info.LastWriteTimeUtc.Ticks;
        long length = info.Length;
        lock (LoadLock)
        {
            if (HashCache.TryGetValue(filePath, out (long WriteTicks, long Length, string Hash) cached)
                && cached.WriteTicks == writeTicks
                && cached.Length == length)
            {
                return cached.Hash;
            }
        }

        byte[] bytes = File.ReadAllBytes(filePath);
        string hash = Convert.ToHexString(SHA256.HashData(bytes));
        lock (LoadLock)
        {
            HashCache[filePath] = (writeTicks, length, hash);
        }

        return hash;
    }

    private static void EnsureLoaded()
    {
        if (_loadAttempted)
        {
            return;
        }

        lock (LoadLock)
        {
            if (_loadAttempted)
            {
                return;
            }

            _loadAttempted = true;
            string path = ManifestPath;
            if (!File.Exists(path))
            {
                DiagnosticsLog.Info("OfficialManifest", $"Manifest not found at '{path}'");
                _hashes = null;
                return;
            }

            try
            {
                string json = File.ReadAllText(path);
                ManifestDto? dto = JsonSerializer.Deserialize<ManifestDto>(json, JsonOptions);
                if (dto?.Levels is null || dto.Levels.Count == 0)
                {
                    _hashes = null;
                    return;
                }

                _hashes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                foreach ((string key, string value) in dto.Levels)
                {
                    if (!string.IsNullOrWhiteSpace(key) && !string.IsNullOrWhiteSpace(value))
                    {
                        _hashes[key] = value.Trim();
                    }
                }

                DiagnosticsLog.Info("OfficialManifest", $"Loaded {_hashes.Count} official level hash(es)");
            }
            catch (Exception ex)
            {
                DiagnosticsLog.Info("OfficialManifest", $"Failed to load manifest: {ex.Message}");
                _hashes = null;
            }
        }
    }

    private sealed class ManifestDto
    {
        [JsonPropertyName("version")]
        public int Version { get; set; } = 1;

        [JsonPropertyName("levels")]
        public Dictionary<string, string>? Levels { get; set; }
    }
}
